addressandportsscreen_manageraddress: ''
addressandportsscreen_newnode: True
upgradeverificationscreen_overwrite: False
licensescreen_license: ''
databasescreen_databasetype: 'PostgreSQL'
databasescreen_port: 5432
databasescreen_hostname: ''
databasescreen_transport: 'TCP'
databasescreen_databasename: 'dsmdb'
databasescreen_username: 'dsm'
databasescreen_password: 'trendmicro'
addressandportsscreen_managerport: 4119
addressandportsscreen_heartbeatport: 4120
credentialsscreen_administrator_username: 'masteradmin'
credentialsscreen_administrator_password: 'trendmicro'
credentialsscreen_usestrongpasswords: False
securityupdatescreen_updatecomponents: True
securityupdatescreen_proxy: False
securityupdatescreen_proxytype: ''
securityupdatescreen_proxyaddress: ''
securityupdatescreen_proxyport: ''
securityupdatescreen_proxyauthentication: False
securityupdatescreen_proxyusername: ''
securityupdatescreen_proxypassword: ''
softwareupdatescreen_updatesoftware: True
softwareupdatescreen_proxy: False
softwareupdatescreen_proxytype: ''
softwareupdatescreen_proxyaddress: ''
softwareupdatescreen_proxyport: ''
softwareupdatescreen_proxyauthentication: False
softwareupdatescreen_proxyusername: ''
softwareupdatescreen_proxypassword: ''
relayscreen_install: True
smartprotectionnetworkscreen_enablefeedback: True
